name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      # Linux binary
      - name: Collect Linux binary
        if: runner.os == 'Linux'
        run: |
          mkdir -p dist
          cp target/release/twdl dist/twdl-linux

      # macOS binary
      - name: Collect macOS binary
        if: runner.os == 'macOS'
        run: |
          mkdir -p dist
          cp target/release/twdl dist/twdl-macos

      # Windows binary
      - name: Collect Windows binary
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          mkdir dist
          Copy-Item target/release/twdl.exe dist/twdl-windows.exe

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}